### PR TITLE
bump package.json to 1.3.0

### PR DESCRIPTION
**Pull request by drcmda**
I think we forgot to bump it. The npm package is outdated, too. The syntax on the frontpage wouldn't work with 1.2.

### CODE REVIEW

**Review by wKovacs64 — CHANGES_REQUESTED** [review]
Let's bump minor instead since we added backward-compatible functionality.

**Comment by tizmagik** [comment]
Yeap, sorry, I didn't get a chance to bump and publish a new version. Let's make it `1.3.0` and I can publish that.

**Comment by tizmagik** [comment]
@wKovacs64 we good to go?

**Review by wKovacs64 — APPROVED** [review]

**Comment by wKovacs64** [comment]
@tizmagik We should probably merge #23 first so it gets included in the package. Either way, this looks good now. Thanks @drcmda.

**Comment by tizmagik** [comment]
@wKovacs64 sure, if you have a minute please review #23  and I can publish after it gets merged.

**Pull request merged**
