### PR TITLE
Adds server-side rendering

### LINKED ISSUE #24: Server-side Rendering
Isomorphic/universal React is a thing and react-csjs should probably support it in some capacity. Out of the box, it won't work in that environment because it inserts styles into the global `document` object in the component lifecycle methods, which doesn't exist server-side.

We should probably either solve it internally (not sure how or if that's even possible), or provide documentation on how to do it externally. I have a first-stab ~demo~ (edit: now defunct) of solving it externally, but I'm not sure if it's the right approach (I've never personally done server-side rendering, so I'm treading deep water here).

Thoughts, @tizmagik ?

### PR DESCRIPTION
**Pull request by tizmagik**
Closes #24 

See example/server/index.js for how it works

Still TODO:
- [x] Test /server
- [x] Documentation

cc @wKovacs64

### CODE REVIEW

**Review by wKovacs64 — COMMENTED** [review]
I was thinking about including the styles within the rendered component, negating the need to remove them in the client bundle. But the way you have it now will provide the flexibility to do that if desired, so that's cool.

Something like this:

```
app.get('/', (req, res) => {
  const renderedApp = ReactDOMServer.renderToString(<App />);
  // imagine some templating going on
  res.render('index', {
    root: `
      <div id="root">
        <style>${getStyle()}</style>
        ${renderedApp}
      </div>
    `,
  });
});
```

**Comment by wKovacs64** [comment]
I wonder if we should split this example off on its own (separate from the basic one), in the spirit of simplicity. Not everyone will be doing SSR and it might add unnecessary confusion? Just pondering here... :thinking:

**Comment by tizmagik** [comment]
> I was thinking about including the styles within the rendered component, negating the need to remove them in the client bundle.

Removing the styles is not _strictly_ necessary, but not doing so means you'll have the styles defined twice. Ideally, client-side rendered (CSR) styles would be aware of the styles that were SSR and would no-op the "insert styles" step, but that's out of scope for this PR. Maybe we can create an issue to do that later.

> I wonder if we should split this example off on its own

We could, but I think the boundaries around SSR and CSR are clear enough. What I can do is add some extra explanatory comments making sure it's clear what's necessary when only doing CSR. Let me try that and see what you think.

**Comment by wKovacs64** [comment]
> Removing the styles is not strictly necessary, but not doing so means you'll have the styles defined twice.

Sure. I had other things in mind beyond skirting the removal process, like templating and other stuff where managing the entire document (inserting into `<head>`) could be annoying/undesirable. But as the PR stands now, that won't be a requirement, so I think we're in good shape.

**Comment by tizmagik** [comment]
@wKovacs64 ready for full review when you have a chance please. Thanks!

**Review by wKovacs64 — APPROVED** [review]

**Pull request merged**
